travis:
  secure:
    BINSTAR_TOKEN: BkrdJnl2Q666Uq4yDA9K6HDzHHpVJj31KIgnkL+h5xiB+xAX9WGFndUnlrTPPtwrETc5aOePYeL0fuxyd3eUEHbjNKII2qLr1VTKyZ/Mn11DSm/pvR1oLyVpJ36aLDUn/mnPnrNJn0/E5klttFRYtnm7QQ3ygIPZVsJCYo1LDeM/KpM63H/EPPefm9K33tmXu155fk0iHjKMpGID1osh0tieIWcrgbrvkjoOuAYmeo7lLf1U0zVasWoD469jOcY65z+1VkAgF0Yle5Zek2AohVQHl8vByIRR5VM4liY2t0VpNdISoUG/spLKDYCnD1RWtHbJh+svLWdIaalEXK2jXbJDcfPH2RLFsBjRzIwENfc6a6oTMOMX+0iFbFc6Ms6TuZdkdfhP6Uyl3QvkYSX20l6AqDqvQSOugzZabvLm0U7W8PlSb6AYOVBsnDngoycB/2QIuvp/y2vkkfUyHfNt3sIYaxuw4jpHzHzIeoYrXgAyKQ/7NY6kIwpBZyGBHmHKrVF8YmOxOjSGu7nJb7vUQDIVdsJOOuy0PMB1fcrqY8QobRmWEKVgWUFbnUal8k000xExfNATxg7fJGsjiCfG9XuceS5jVYm2m2py3hKeq24yjtc5hSiBwIeho5f/YoBEtQXUbKOInRr/yc5ezLko4zqUVzcBx5BlKpxFGcb555U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
