travis:
  secure:
    BINSTAR_TOKEN: kmhrY911sgfwn6pPPJmIeyFUJX58SrAMjHE1lVe+wDhuTAs2P73Af+62VygqTxZ58omczkhskihB6IPMf5Hl8MSIi6Z6RAqFRBPIqMPpskvbyl9kWJyDunjoGSp4inxzDUxYc4tgjrlqtyJ7boIj4580MNTLZvkBGP5H6j00ji+VaFkjYXVPKZ9ImLb+U9tUtuN0vD+zmyGivOjD+Xk0Rcew2oU3gcq5oaNyHlWTE0Us1s8645qoIIatQregBK6woE3ixVGxMclI9t5yOqeMQaiCMSo9wLeyp57gwSta3pTkQVXIfXtoxbziRFSl2y/xRB1ei8WuBIT/u3rppCtRjXU4UzDxgWzRtIY70DHT/mJ0Jz9QLUtgCCq8/tuZG7GD0ohMTwCJNkDXGbCRcD2kr4vSZm3HSb29dbiRyn+6GaOULVdiEPPernK8CldQYhPwbfAbGXSQVcY3RCnlFpKRBFrJI05foZYGNcUeVScr1pqUJ2+IzcGBgM0UQVvRk6H6mJz7e0gtNff7AJ+ZsfYQTdL5iWUoFmtIKMJj9kqZsCJmaSd2Q8rnihE96YTSKnEHrGV6HuE5dLd9VQ+moI9vlFzxDqE0FRis8lu5y1hSAVzEywtC9YKFm8l2BWI/xcDiq8xIQv0rlqiJtMfAJc0TL2uN+2rv1m7FW8zNdoA4hIA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
