travis:
  secure:
    BINSTAR_TOKEN: BIFL1+dV0Mhx8QQoBszFNrtq/HwoIwWl7lBEXmc7dD6CUSVFp09QqA6PjQr56rLX0j1Df5y1nsvHpwjUKxHl7EHxO0GaybCtzQ6FavL0LcVUO35mjDaLqh125KQXe5EmD0dNX5g4xO8veYVqCujUM3DStgnbUVV1LiXgJYHYZLK2KoIds7TOqOWaW7GmtbXTqj/qgJLrBSOMYgggldMYcgePdMZUJ06pEfeZ9trClwT3hoWtK2YQKXXZ1LWbmOSgKGfk19AgGm/ZNcP65ibuMzuPeExnj8ZHKhDkRUvsuopgndlM5QVzCzsyZ/jkXU/trLCTJVX55bAJhQU6j2WgsZMReXQjTfL9Xe4lD1ciLa7jBoYsMNdEDw140LzybhqgnO/Azw4YqNILGy3qadnAeh0BLyX9TXIc6x68KyqpKfgjZVYUMM5uLxMYt5VB6ZeSgt0CmIPvvlhWDb3VUpiJ0FladxTnPyOqp+yOvCNYsgdjhuCGqkEiub+PktMuZBsxvWhFVmJVb5bBgasXCo5mpzJO21keY2QH0EjHqyGmOhq6AaFhzlZsaHhw0tIZ9s5kesSawAMZqDkZ6TsyqSFw4QdpGBTJnZTbiVcKXnHovkgKkJvB52fVJ/asnrgRtNIx2Eg+6nB3fW1fIQtQKWQs4FCNXaWTQDtabRNAqHvylck=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
